apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cue-controller
  namespace: system
  labels:
    app: cue-controller
spec:
  selector:
    matchLabels:
      app: cue-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: cue-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        # - --events-addr=http://notification-controller.flux-system.svc.cluster.local/
        - --watch-all-namespaces=true
        - --log-level=info
        - --log-encoding=json
        - --enable-leader-election
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: phoban01/cue-controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: cue-controller
      terminationGracePeriodSeconds: 10
