apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cuedemo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/phoban01/cuedemo
  ref:
    branch: main
---
apiVersion: cue.contrib.flux.io/v1alpha1
kind: CueInstance
metadata:
  name: podinfo-dev
  namespace: default
spec:
  interval: 5m
  moduleRoot: "./examples/podinfo"
  expressions:
  - out
  tags:
  - key: hpa
  prune: true
  sourceRef:
    kind: GitRepository
    name: cuedemo
